name: CI

on:
  push:
    branches:
      - "main"
    paths:
      - "**.jsx?"
      - "**.tsx?"
      - "lib/**"
      - "test/**"
      - ".github/workflows/ci.yml"
  pull_request:
    paths:
      - "**.jsx?"
      - "**.tsx?"
      - "lib/**"
      - "test/**"
      - ".github/workflows/ci.yml"

permissions:
  contents: read

env:
  default_node_version: "lts/*"

jobs:
  lint_es:
    name: Lint es
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.default_node_version }}
          architecture: x64
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm i

      - name: lint:es
        run: |
          pnpm run lint:es

  lint_ext:
    name: Lint web-ext
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.default_node_version }}
          architecture: x64
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm i

      - name: lint:ext
        run: |
          pnpm run lint:ext

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.default_node_version }}
          architecture: x64
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm i

      - name: Build
        run: |
          pnpm run build
